# Site
name: "israelo Blogs"
title: "israelo Blogs"
description: "I will take you on the fabulous world of exploration. Travel, culture, lifestyle. Eat, Pray, Love!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /blog.israelo
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'disqus_npUAeUKkjE'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: israel@iospire.com

#-------------------------------
# Hero Settings
hero:
  name: Israel Ogbole
  image: https://user-images.githubusercontent.com/2548160/103445496-98488300-4c6c-11eb-9d7e-7c02104a908e.png
  say-hello: Hello, I’m <strong>Israel Ogbole</strong>
  bio: I am a Technical Solution Architect, and my background stems from Software Engineering. I will use this space to share personal experiences with Arduino IoT, Raspberry Pi, Cloud Native technologies, and the likes. Also, I will journal Naomi's programming journey here.  Naomi is my eight-year-old daughter who loves coding and is about to graduate from scratch to core python.  
  twitter: https://twitter.com/israel_ogbole # Add your Twitter handle
  #facebook: https://facebook.com/ # Add your Facebook handle
  #instagram: https://instagram.com/ # Add your Instagram handle
  linkedin: https://www.linkedin.com/in/israelo
  github:  https://github.com/iogbole


# Authors
authors:
  israel:
    name: Israel
    display_name: Israel
    gravatar: 77792bd6ee4b9ddd999d004c6e8d9b2d
    email: israel@israelo.io
    web: https://www.linkedin.com/in/israelo/
    twitter: https://twitter.com/israel_ogbole
    description: "Parent, Engineer and a  Blogger. "

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
